
services:
  shopcart_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopcart_service
    command: ["uv", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--proxy-headers"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./src:/app/src:rw
      - ./uv.lock:/app/uv.lock:rw
      - ./pyproject.toml:/app/pyproject.toml:rw
      - ./.cache/uv:/home/appuser/.cache/uv  # fix permission denied errors
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${db_user:-postgres}
      POSTGRES_PASSWORD: ${db_password:-4444}
      POSTGRES_DB: ${db_name:-shopcart_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
