name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Authenticate Docker with GCP
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      # Step 4: Build and push Docker image
      - name: Build & push Docker image
        run: |
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/shopcart-api:${GITHUB_SHA}"
          docker build -t $IMAGE .
          docker push $IMAGE

      # Step 5: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy shopcart-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/shopcart-api:${GITHUB_SHA} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }}"
